### ISSUE TITLE
Colour and Style

### ISSUE THREAD

**Issue by violaberg** [ai-avenger-teams/rebuild-ireland-backend#10]
As a ***developer*** I can ***choose color palette and style of the app*** so that ***I can have a clear vision of end result***

### Tasks:

- [ ] Create color palette once colors have been chosen

- [ ] Decide the style of project

- [ ] Choose logo and background to suit the chosen style and colors
