### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by violaberg** [ai-avenger-teams/rebuild-ireland-backend#12]
As a ***developer*** I can ***create user-friendly error pages*** so that ***I can guide user safely back to home page.***

### Tasks:

- [x] Create 403, 404, 500 error pages

- [x] Customize to project's style

- [x] Add 'Back to home page' button on each page
