### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by violaberg** [ai-avenger-teams/rebuild-ireland-backend#13]
As a ***user*** I can ***easily navigate app*** so that ***I enjoy using app without getting lost***

### Acceptance criteria:

1. Easy to navigate navbar

2. Back to home button where needed

3. Responsive navbar
4. Back to top button

### Tasks:

- [ ] Create responsive navbar with burger menu for mobile devices

- [ ] Ensure home button is available where necessary 

- [ ] Create back to top button where needed
