### ISSUE TITLE
ChatBot

### ISSUE THREAD

**Issue by DarrachBarneveld** [ai-avenger-teams/rebuild-ireland-backend#17]
As a ***user*** I can ***enter my questions into a input box*** so that I can ***interact with the chatbot***

### Acceptance criteria:

1. Create a basic input and chat thread UI.
2. Implement full CRUD functionality with API endpoints.
3. Handle all errors.

### Tasks:

- [ ] Design and create a basic UI for the chatbot.
- [ ]  Render the bot's responses in a clear, thread-like manner.
- [ ]  Display associated data, such as graphs or relevant links, in a designated area.
- [ ]  Implement all CRUD functionality.
- [ ]  Handle loading states and error states.
- [ ]  Save thread logs to ensure persistence for the user.
