### ISSUE TITLE
Contact app

### ISSUE THREAD

**Issue by violaberg** [ai-avenger-teams/rebuild-ireland-backend#20]
As a ***developer*** I can ***create Contact app*** so that I can ***ensure contact form is fully functional.***

### Acceptance criteria:

1. Contact app created and connected to project

2. Model, view, serializer created

### Tasks:

- [ ] Start Contact app
- [ ] Update settings and urls

- [ ] Create Contact model

- [ ] Create Contact serializer
- [ ] Create Contact view
