### ISSUE TITLE
🐛 [Bug]: Model: Fine Tuning -> Vector Storage | Prompts

### ISSUE THREAD

**Issue by ai-avengers-team** [ai-avenger-teams/rebuild-ireland-backend#23]
#### Fine Training
@stephendawsondev has
- [ ] the file train_model.py that loads the txt data, then 
- [ ] ... tune_model.py that is meant to store the prompts 
- [ ] as vectors in the DB (locally).

Use The technique I'm trying is "few-shot prompts", but it may actually be necessary to properly tune the model.

#### Deprecation Errors
There are some deprecation errors when running python tune_model.py , so that might be worth looking into.

### Expected Behavior

To be updated @jhoanTrujillo or @stephendawsondev 
Or by @ai-avengers-team 

### Steps to Reproduce

@ai-avengers-team Today.

#### As Is
- GCP
- GOOGLE_API_KEY=YOUR-API-KEY <sup>(no actual key)</sup>
- Vector DB Local
- Python
- Streamlit
- Few Shots Prompts

#### To Be
- [ ] GCP
- [ ] GOOGLE_API_KEY=YOUR-API-KEY <sup>(no actual key)</sup>
- [ ] Vector DB - as managed service
- [ ] Streamlit
- [ ] Python

### Replication
You need to:
```python
set up a .venv with python3 -m venv .venv
Change to the venv using source .venv/bin/activate (run in twice in case)
Run pip install -r requirements.txt
Add a .env file and add this to it GOOGLE_API_KEY=YOUR-API-KEY
Run python train_model.py
Run python tune_model.py (this may be the wrong step and we may need to tune it differently)
Run streamlit run main.py
```

## Todo

- [x] I / we have a shared instance to work from (I need to get similar up to speed).
- [x] Investigate - Local or remote DV storage for Prompts
- [x] Replicate the issue 
- [ ] Check the repo reference:  take: https://github.com/ai-avenger-teams/practice-ai-repo
- [ ] Depreciation errors
- [ ] Q&A for Mentor
- [x] How much data ( need for more raw )
- [x] Rerun the model / eval the workflow / refine the process.

## Contact the Mentor

If you're going to a mentor:
1. How to train the model using unstructured data (and use my example)
2. How to tune the model OR prompt it using the sample prompts I've added
3. Like @jhoanTrujillo says, hosting a vector DB (right now it's local).

> For the training and tuning, find out how much data we need (we likely don't have enough). AND if you can run them through what we've done and just ask if we're missing any steps.
