### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by violaberg** [ai-avenger-teams/rebuild-ireland-backend#25]
As a ***user*** I can ***read Terms of Service*** so that I can ***understand the rules and guidelines***

### Acceptance criteria:

1. Clearly written Terms of Service

2. Style aligns with the rest of project

3. Link in the footer

### Tasks:

- [ ] Create Terms of Service page

- [ ] Generate Terms of Service

- [ ] Style the page

**Comment by violaberg** [comment]
Page created, terms of service to be added
