### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by violaberg** [ai-avenger-teams/rebuild-ireland-backend#6]
As a ***user*** I can ***easily navigate to contact form*** so that I can ***receive any additional information needed***

### Acceptance criteria:

1. Responsive and easy to use contact form with necessary fields

2. Site should prominently display contact information, such as a contact form and/or email address

3. Email confirmation page after message has been sent successfully

### Tasks:

- [ ] Create Contact page

- [ ] Ensure form can be submitted successfully

- [ ] Create email confirmation
- [ ] Add contact info/ link in footer
