### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by violaberg** [ai-avenger-teams/rebuild-ireland-backend#7]
As a ***new user*** I can ***register on site*** so that I can ***save my personal information and track progress***

### Acceptance criteria:

1. User friendly sign up form
2. User receives a confirmation message upon successful registration

3. User data stored and processed securely

4. Validation for user input
5. Progress tracker in profile

### Tasks:

- [ ] install Django allauth

- [ ]  Create the registration API endpoint in the backend

- [ ] Implement the registration form on the frontend

- [ ] Validate user input (username, email, password)

- [ ] Handle form submission and save user data to the backend

- [ ] Display success or error messages based on the registration outcome
- [ ]  Redirect to email sent page

 - [ ] Style the signup page
