### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by violaberg** [ai-avenger-teams/rebuild-ireland-backend#9]
As a ***logged-in user*** I can ***view and edit my profile*** so that I can ***update my personal information and track my progress.***

### Acceptance criteria:

1. User can view their profile information (username, email)

2. User can update their profile information

3. Changes to the profile are saved and reflected immediately
4. Progress tracker for grant/ renovation process

### Tasks:

- [ ] Implement the profile view and edit forms on the frontend

- [ ] Fetch and display current profile information

- [ ] Handle profile update submissions and save changes
- [ ] Display success or error messages based on the update outcome
- [ ] Add progress tracker
